image: node:8.11.1

variables:
  GIT_STRATEGY: fetch

stages:
  - setup
  - test
  - deploy

.master-only: &master-only
  only:
    - master
  except:
    - tags
    - schedules
    - triggers

npm:install:
  stage: setup
  script:
    - npm i
  artifacts:
    expire_in: 1 day
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/

unit_test:
  stage: test
  script:
    - npm test
  # grabs code coverage (% of lines) from jest output
  coverage: /Lines.*\s([\d\.]+)\%/

# =============================================
# DEPLOY
# =============================================
deploy_app:
  stage: deploy
  only:
    - release
  except:
    - tags
    - schedules
    - triggers
  script:
    # @TODO wire up to actual deploy script
    # - docker info
    # - ./docker/scripts/docker_deploy.sh $ENVIRONMENT $CI_COMMIT_SHA

