image: node:10.14.1-alpine

variables:
  GIT_STRATEGY: fetch

stages:
  - setup
  - test
  - deploy

##############################
# Define yml anchors
##############################

.master-only: &master-only
  only:
    - master
  except:
    - tags
    - schedules
    - triggers

ui:install:
  <<: *master-only
  stage: setup
  artifacts:
    expire_in: 1 day
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - client/node_modules/
  script:
    - cd client
    - npm i

ui:unit_test:
  <<: *master-only
  stage: test
  script:
    - cd client
    - npm test
  # grabs code coverage (% of lines) from jest output
  coverage: /Lines.*\s([\d\.]+)\%/

# =============================================
# DEPLOY
# =============================================
deploy_app:
  stage: deploy
  only:
    - release
  except:
    - tags
    - schedules
    - triggers
  script:
    # @TODO wire up to actual deploy script
    - echo 'Hello World'
    # - docker info
    # - ./docker/scripts/docker_deploy.sh $ENVIRONMENT $CI_COMMIT_SHA

