services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ttis-db:
    container_name: db
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: ttis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ttis-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ttis-api:
    container_name: api
    restart: on-failure
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@ttis-db:5432/ttis_db
    depends_on:
      - ttis-db
    ports:
      - 4000:4000

  ttis-ui:
    container_name: ui
    restart: on-failure
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    depends_on:
      - ttis-api
    ports:
      - 3000:3000

volumes:
  ttis-data:
