services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ttis-db:
    container_name: db
    image: postgres:16-alpine
    restart: on-failure
    env_file: ./packages/api/.env
    volumes:
      - ttis-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ttis-api:
    container_name: api
    restart: on-failure
    build:
      context: ./packages/api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://postgres:password@ttis-db:5432/ttis_db
    depends_on:
      - ttis-db
    ports:
      - 4000:4000
    volumes:
      - ./packages/api:/usr/src/app:rw
      # We don't want modules installed on host platform to be used on container,
      # so we're effectively hiding node_modules from the host (must be in this order)
      - ttis-api-node-modules:/usr/src/app/node_modules

  ttis-ui:
    container_name: ui
    restart: on-failure
    build:
      context: ./packages/ui
    env_file: ./packages/ui/.env
    volumes:
      - ./packages/ui:/usr/app
      # Prevent host node_modules from overwriting container's installed modules
      - ttis-ui-node-modules:/usr/app/node_modules
    depends_on:
      - ttis-api
    ports:
      - 3000:3000

volumes:
  ttis-data:
  ttis-api-node-modules:
  ttis-ui-node-modules:
